# Generated by Django 2.2.1 on 2019-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shift', models.CharField(max_length=255)),
                ('buffer_time', models.TimeField()),
                ('cutoff_time', models.TimeField()),
                ('contact_no', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
